### ISSUE TITLE
nbind is deprecated, use denodeify

### ISSUE THREAD

**Issue by ernestohegi** [rafaelkaufmann/q-orm#6]
This error message appears when running tests on the terminal on database connection:

nbind is deprecated, use denodeify (with caveats) instead. Error
    at Function.Q_deprecate [as nbind] (.../node_modules/q-orm/node_modules/q/q.js:166:21)
    at setupConnectionMethods (.../node_modules/q-orm/lib/q-orm.js:88:28)
    at Promise_then_fulfilled (.../node_modules/q-orm/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (.../node_modules/q-orm/node_modules/q/q.js:835:31)

**Comment by diegosucaria** [comment]
![screen shot 2017-04-09 at 3 55 09 pm](https://cloud.githubusercontent.com/assets/4278322/24840099/2b3bbf3c-1d3d-11e7-981c-93084ec822fc.png)

Seeing a similar error
